name: Gradle CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Specify the JDK distribution (temurin is recommended)
          java-version: '11'

      # Step 3: Cache Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Grant execute permissions for the Gradle wrapper
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      # Step 5: Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 6: Run tests
      - name: Run tests
        run: ./gradlew test
